Repository MicrosoftDocs/windowsserverdocs, pull requests merged in 2020-06, with the labels that each got.

#3788 Update applies to section to include Server 2019
  WindowsServerDocs/administration/windows-server-update-services/deploy/deploy-windows-server-update-services.md
Labels: WSUS

#3787 Updated applies to section to include Server 2019
  WindowsServerDocs/administration/windows-server-update-services/get-started/windows-server-update-services-wsus.md
Labels: WSUS

#4472 ADDS/Capacity Planning: remove forgotten comment
  WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md
Labels: in progress

#4481 Get Started/Troubleshoot KMS/DNS: typo correction
  WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md
Labels: in progress

#4430 RDP file settings/RemoteApp: remoteapplicationexpandworkingdir
  WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md
Labels: remote-desktop-services

#4510 Update gatewaycredentialssource values in rdp-files.md
  WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md
Labels: remote-desktop-services

#4442 Updated to clarify KB required
  WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md
Labels: AD FS

#4491 Changing the title
  WindowsServerDocs/identity/ad-fs/design/AD-FS-Design-Guide.md
Labels: AD FS

#4591 Fixed DNS instruction issues
  WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md
Labels: AD FS

#4513 ADDS/Deploy: Azure Virtual Network supports IPv6
  WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md
Labels: AD DS

#4576 Link update Securing Privileged Access
  WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md
Labels: needs-contributor-update

#4602 Update netstat.md
  WindowsServerDocs/administration/windows-commands/netstat.md
Labels: windows-commands

#4347 Clarify usage of Semi Annual Channel for SDDS
  WindowsServerDocs/get-started-19/servicing-channels-19.md
Labels: get started 19
